import os
import sys
import shutil

def get_appdata_path():
    # Detect if we are in WSL or native Windows
    if 'USERPROFILE' in os.environ:
        # Native Windows
        return os.path.join(os.environ['USERPROFILE'], 'AppData', 'LocalLow', 'KyraCo', 'Sword Scuffle')
    else:
        # Check if in WSL
        try:
            with open('/proc/version', 'r') as f:
                if 'microsoft' in f.read().lower():
                    # We are in WSL. Try to find the Windows username dynamically.
                    user_paths = ['/mnt/c/Users/nouuu', f'/mnt/c/Users/{os.environ.get("USER", "nouuu")}']
                    for up in user_paths:
                        # Unity path is case-sensitive in WSL, but AppData and LocalLow are usually standard
                        path = os.path.join(up, 'AppData', 'LocalLow', 'KyraCo', 'Sword Scuffle')
                        if os.path.exists(path): return path
                    
                    # Last resort fallback to common path
                    return '/mnt/c/Users/nouuu/AppData/LocalLow/KyraCo/Sword Scuffle'
        except:
            pass
    return 'AppData/LocalLow/KyraCo/Sword Scuffle'

def collect_metrics_to_scenario(scenario_name):
    """
    Copies the real metrics generated by the game from AppData to the results folder.
    """
    base_path = get_appdata_path()
    server_src = os.path.join(base_path, 'server_logs.csv')
    client_src = os.path.join(base_path, 'client_logs.csv')

    results_dir = os.path.join('results', scenario_name)
    os.makedirs(results_dir, exist_ok=True)

    if os.path.exists(server_src):
        # We rename them to _metrics.csv so process_results.py finds them automatically
        shutil.copy(server_src, os.path.join(results_dir, 'server_metrics.csv'))
        print(f"Scenario '{scenario_name}': Collected server metrics.")
    else:
        print(f"Warning: {server_src} not found.")

    if os.path.exists(client_src):
        shutil.copy(client_src, os.path.join(results_dir, 'client_metrics.csv'))
        print(f"Scenario '{scenario_name}': Collected client metrics.")
    else:
        print(f"Warning: {client_src} not found.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python collect_metrics.py <scenario_name>")
    else:
        collect_metrics_to_scenario(sys.argv[1])
